apps:
  upkeep:
    command: 'bin/upkeep'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/upkeep/issues'
description: 'Portage update helper commands.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/upkeep/issues'
license: 'MIT'
name: 'upkeep'
parts:
  upkeep:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/upkeep'
summary: 'Portage update helper commands.'
title: 'upkeep'
version: '1.6.1'
website: 'https://tatsh.github.io/upkeep/'
